[programs.devnet]
myepicproject = "36yiiH5JMQMr9bhqgdDgKhJ4aBcr3nfhCE1XTH8geeRu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/michael/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
